apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,scamazon"
data:
  database_url: mongodb-service
  database_port: "27017"
  # database_name:
