name: Fetch Docker Image Tags

on:
  push:
    branches:
      - main

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Fetch Docker Image For home 
        run: |
            API_URL="https://registry.hub.docker.com/v2/repositories/passwordnotsafe/home-page-service/tags"
            RESPONSE=$(curl -s "$API_URL")
            echo "API Response:"
            echo "$RESPONSE"
            TAGS=$(echo "$RESPONSE" | jq -r '.results[] | select(.name != "latest" and .name != "1.0.0") | .name')
            
            echo "$TAGS"
