name: Fetch Docker Image Tags

on:
  push:
    branches:
      - main

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Fetch Docker Image For home-page-service 
        run: |
            API_URL="https://registry.hub.docker.com/v2/repositories/passwordnotsafe/home-page-service/tags"
            RESPONSE=$(curl -s "$API_URL")
            TAGS=$(echo "$RESPONSE" | jq -r '.results[] | select(.name != "latest" and .name != "1.0.0") | .name')
            
            #path = $(git ls-files | grep "home-page-development.yml")
            

            # Ersätt den gamla taggen med den nya taggen i Deployment-filen med hjälp av sed
            sed -i "s|image: passwordnotsafe/home-page-service:.*|image: passwordnotsafe/home-page-service:$NEW_TAG|g" frontpage/home-page-development.yml

            # Visa innehållet i den uppdaterade Deployment-filen för att verifiera ändringen
            cat frontpage/home-page-development.yml
