name: Fetch Docker Image Tags for Product - Trigger from another repo

on: workflow_dispatch

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Fetch Docker Image Tags for product-catalog-service 
        run: |
            API_URL="https://registry.hub.docker.com/v2/repositories/passwordnotsafe/produkt-catalog-service/tags"
            API_CALL=$(curl -s "$API_URL")
            NEW_TAG=$(echo "$API_CALL" | jq -r '[.results[] | select(.name != "master" and .name != "latest")] | sort_by(.last_updated) | .[-1].name')            

            # Ersätt den gamla taggen med den nya taggen i Deployment-filen med hjälp av sed
            sed -i "s/produkt-catalog-service/produkt-catalog-service:$NEW_TAG/g" frontpage/product-catalog-deployment.yml

            # Visa innehållet i den uppdaterade Deployment-filen för att verifiera ändringen
            cat frontpage/product-catalog-deployment.yml
